vids = {
    "kind": "youtube#searchListResponse",
    "etag": "xSnCDk1JnXAPqomHPPFKGgqmia8",
    "nextPageToken": "CDIQAA",
    "regionCode": "PL",
    "pageInfo": {"totalResults": 387, "resultsPerPage": 50},
    "items": [
        {
            "kind": "youtube#searchResult",
            "etag": "bycIB5O4Czxh98pYaJ5hoQbsU7M",
            "id": {"kind": "youtube#video", "videoId": "ACySmbsgph8"},
            "snippet": {
                "publishedAt": "2025-07-26T13:30:06Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "AI “Destroys” Months of Work",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/ACySmbsgph8/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/ACySmbsgph8/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/ACySmbsgph8/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-07-26T13:30:06Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "iJnN5jKHzm7VQiFMOaaoixAJAk0",
            "id": {"kind": "youtube#video", "videoId": "tKHEEC-CBYY"},
            "snippet": {
                "publishedAt": "2025-06-17T12:48:43Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "THIS IS THE REAL VIBE CODING",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/tKHEEC-CBYY/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/tKHEEC-CBYY/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/tKHEEC-CBYY/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-06-17T12:48:43Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "Vx25BCRLzKBeko_VPMxWi2sJDlA",
            "id": {"kind": "youtube#video", "videoId": "alGhS9CEgCg"},
            "snippet": {
                "publishedAt": "2025-06-08T17:27:20Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Stack Overflow Is Almost Dead",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/alGhS9CEgCg/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/alGhS9CEgCg/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/alGhS9CEgCg/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-06-08T17:27:20Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "mYiLr0Aoez8Hh8MY3JMoj1hLl70",
            "id": {"kind": "youtube#video", "videoId": "AWZ9AgjPfwo"},
            "snippet": {
                "publishedAt": "2025-06-07T15:45:33Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Dopamine Driven Development",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/AWZ9AgjPfwo/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/AWZ9AgjPfwo/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/AWZ9AgjPfwo/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-06-07T15:45:33Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "l-zRcdl5PO2o70T5PJuVsgOTSR4",
            "id": {"kind": "youtube#video", "videoId": "TTgcNCyxJTs"},
            "snippet": {
                "publishedAt": "2025-05-20T15:49:48Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Cybersecurity Nightmare",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/TTgcNCyxJTs/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/TTgcNCyxJTs/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/TTgcNCyxJTs/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-05-20T15:49:48Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "GKAG8Ckt44ji8sSu9jfkqem1CUg",
            "id": {"kind": "youtube#video", "videoId": "sfT6sMkj6Ow"},
            "snippet": {
                "publishedAt": "2025-05-18T15:01:20Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Coding Should Be A Vibe",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/sfT6sMkj6Ow/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/sfT6sMkj6Ow/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/sfT6sMkj6Ow/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-05-18T15:01:20Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "bUF4QZVbDqIF4W3f7I-Yv1LExuQ",
            "id": {"kind": "youtube#video", "videoId": "LhKau4K6Pqc"},
            "snippet": {
                "publishedAt": "2025-05-17T14:00:27Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Don&#39;t Let Architecture Astronauts Scare You",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/LhKau4K6Pqc/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/LhKau4K6Pqc/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/LhKau4K6Pqc/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-05-17T14:00:27Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "YwLlI6z19df9Qot6__8U9OhQp2w",
            "id": {"kind": "youtube#video", "videoId": "jnY61ywnBHM"},
            "snippet": {
                "publishedAt": "2025-05-14T18:10:08Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "JUST USE HTML",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/jnY61ywnBHM/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/jnY61ywnBHM/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/jnY61ywnBHM/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-05-14T18:10:08Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "etB2y4P-mchZ_iP-jBXE2N-qqZU",
            "id": {"kind": "youtube#video", "videoId": "KewNj_sJ9Bs"},
            "snippet": {
                "publishedAt": "2025-05-12T20:20:21Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "I&#39;VE HAD ENOUGH!!!",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/KewNj_sJ9Bs/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/KewNj_sJ9Bs/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/KewNj_sJ9Bs/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-05-12T20:20:21Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "5xVyrKlPTiFFuH617CkTfzdODFs",
            "id": {"kind": "youtube#video", "videoId": "-FI4zp7jEso"},
            "snippet": {
                "publishedAt": "2025-05-08T20:20:12Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "OpenAI Buys Windsurf",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/-FI4zp7jEso/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/-FI4zp7jEso/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/-FI4zp7jEso/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-05-08T20:20:12Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "IxqCogi3O4Uql9kGyS1d4oaJe6g",
            "id": {"kind": "youtube#video", "videoId": "wtf3eAdGYKU"},
            "snippet": {
                "publishedAt": "2025-05-07T16:43:06Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "FIVERR CEO Leaks His Own Email",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/wtf3eAdGYKU/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/wtf3eAdGYKU/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/wtf3eAdGYKU/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-05-07T16:43:06Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "SgcLcYluACni76HJAAQQuqM_qTA",
            "id": {"kind": "youtube#video", "videoId": "qjGs89b5ZqY"},
            "snippet": {
                "publishedAt": "2025-05-01T17:54:59Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "The Rise And Fall Of Roy Lee",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/qjGs89b5ZqY/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/qjGs89b5ZqY/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/qjGs89b5ZqY/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-05-01T17:54:59Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "vxE8QydqveZrlcw39t2CVW4lDrQ",
            "id": {"kind": "youtube#video", "videoId": "tb1awv-QWFg"},
            "snippet": {
                "publishedAt": "2025-04-29T14:05:23Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Discord CEO Steps Down",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/tb1awv-QWFg/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/tb1awv-QWFg/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/tb1awv-QWFg/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-04-29T14:05:23Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "efiBLyC64ku6a1E8FIigVMe5kFI",
            "id": {"kind": "youtube#video", "videoId": "U76TSJ7ONzM"},
            "snippet": {
                "publishedAt": "2025-04-22T20:24:12Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Thanks Obama, Al Codes Better Than Most Developers",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/U76TSJ7ONzM/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/U76TSJ7ONzM/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/U76TSJ7ONzM/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-04-22T20:24:12Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "LuPnPZMDrz9OWz3J0OqcJNLKdMw",
            "id": {"kind": "youtube#video", "videoId": "GAxYR2P3v7s"},
            "snippet": {
                "publishedAt": "2025-04-21T21:47:01Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Ex-Google CEO: AI Is Slipping Out of Control",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/GAxYR2P3v7s/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/GAxYR2P3v7s/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/GAxYR2P3v7s/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-04-21T21:47:01Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "9LyGwrUAVme4dTXgiUVOUjIHJgQ",
            "id": {"kind": "youtube#video", "videoId": "sjeie9Y7AZk"},
            "snippet": {
                "publishedAt": "2025-04-12T12:40:42Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "The Insanity of Being a Software Engineer - Prime Reacts",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/sjeie9Y7AZk/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/sjeie9Y7AZk/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/sjeie9Y7AZk/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-04-12T12:40:42Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "bfyav0Aoz07pt7rWeac5m34AxOs",
            "id": {"kind": "youtube#video", "videoId": "MwMaBg7JpDc"},
            "snippet": {
                "publishedAt": "2025-04-11T17:39:02Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Dijkstra on foolishness of Natural Language Programming",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/MwMaBg7JpDc/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/MwMaBg7JpDc/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/MwMaBg7JpDc/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-04-11T17:39:02Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "s3XRSGffTggiJJPfZVYwel2Awcg",
            "id": {"kind": "youtube#video", "videoId": "uFcJTPqeRBE"},
            "snippet": {
                "publishedAt": "2025-04-09T12:00:59Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "I Played Quake But Its Purely AI Generated",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/uFcJTPqeRBE/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/uFcJTPqeRBE/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/uFcJTPqeRBE/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-04-09T12:00:59Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "ivvNaNqIFPgVzRr6KXIMYBn5Dm8",
            "id": {"kind": "youtube#video", "videoId": "u9GTVD7zqRg"},
            "snippet": {
                "publishedAt": "2025-03-27T02:41:59Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Day 5 - VIBE CODING A GAME IN 7 DAYS",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/u9GTVD7zqRg/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/u9GTVD7zqRg/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/u9GTVD7zqRg/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-03-27T02:41:59Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "-04rEtb8Na9S1v1pL-AnBxSKa8Q",
            "id": {"kind": "youtube#video", "videoId": "I-0GhCXdvIQ"},
            "snippet": {
                "publishedAt": "2025-03-26T00:40:23Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Day 4 - VIBE CODING A GAME IN 7 DAYS",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/I-0GhCXdvIQ/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/I-0GhCXdvIQ/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/I-0GhCXdvIQ/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-03-26T00:40:23Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "5XNULWZEP8OGKB6lVkA8V73KK0A",
            "id": {"kind": "youtube#video", "videoId": "BIhCQWwe3LY"},
            "snippet": {
                "publishedAt": "2025-03-24T06:58:57Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Crushing Tower Defense Game Engine - DAY 3 #ad",
                "description": "THE GREATEST STREAM EVER.",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/BIhCQWwe3LY/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/BIhCQWwe3LY/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/BIhCQWwe3LY/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-03-24T06:58:57Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "yTB00RAv2x3479MEIoSix9Uanbs",
            "id": {"kind": "youtube#video", "videoId": "6x3weFV9YI4"},
            "snippet": {
                "publishedAt": "2025-03-22T04:58:47Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Day 1 - VIBE CODING A GAME IN 7 DAYS",
                "description": "I've locked myself in a Tower for 7 days and am going to attempt to build a Tower Defense game using just Cursor! #ad Twitch ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/6x3weFV9YI4/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/6x3weFV9YI4/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/6x3weFV9YI4/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-03-22T04:58:47Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "qNgJY-JQlMfZXU7d60GZLgVN6Nk",
            "id": {"kind": "youtube#video", "videoId": "5qwucCaHpWY"},
            "snippet": {
                "publishedAt": "2025-03-21T14:38:47Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "BUILDING A GAME IN 7 DAYS",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/5qwucCaHpWY/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/5qwucCaHpWY/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/5qwucCaHpWY/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-03-21T14:38:47Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "G6n_gGY9qrhu4ID7U_McKCJRNWg",
            "id": {"kind": "youtube#video", "videoId": "OAKNiSmpDOA"},
            "snippet": {
                "publishedAt": "2025-03-14T14:45:01Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "How To Gain Code Execution | Prime Reacts",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/OAKNiSmpDOA/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/OAKNiSmpDOA/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/OAKNiSmpDOA/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-03-14T14:45:01Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "ZH1XDz7OlO8350NklyW1rVgPfe4",
            "id": {"kind": "youtube#video", "videoId": "oZerk5iKh18"},
            "snippet": {
                "publishedAt": "2025-02-20T21:24:30Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Rust 4 Linux Gets Amazing Update",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/oZerk5iKh18/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/oZerk5iKh18/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/oZerk5iKh18/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-02-20T21:24:30Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "nI3Kw7EjYBM4lclyK32s2R2LUkM",
            "id": {"kind": "youtube#video", "videoId": "eNIBie_uYMI"},
            "snippet": {
                "publishedAt": "2025-02-13T16:25:48Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Proompted Kiddies Learning The Hard Way",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/eNIBie_uYMI/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/eNIBie_uYMI/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/eNIBie_uYMI/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-02-13T16:25:48Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "nSKhJBIqpleE6g3_iVbHzwciKig",
            "id": {"kind": "youtube#video", "videoId": "OkR6-74jq0E"},
            "snippet": {
                "publishedAt": "2025-02-09T16:14:14Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "this is the most hypocritical company in tech",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/OkR6-74jq0E/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/OkR6-74jq0E/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/OkR6-74jq0E/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-02-09T16:14:14Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "m-Nq-HuBhsP-FxNsxvhbEiwjEqU",
            "id": {"kind": "youtube#video", "videoId": "9ZOEtgUkpBM"},
            "snippet": {
                "publishedAt": "2025-02-05T21:37:00Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Jail Time For Downloading DeepSeek??",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/9ZOEtgUkpBM/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/9ZOEtgUkpBM/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/9ZOEtgUkpBM/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-02-05T21:37:00Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "W8DkJ7LSiLPGO8dBzTv5bIEqWec",
            "id": {"kind": "youtube#video", "videoId": "j_R2kk0cMRs"},
            "snippet": {
                "publishedAt": "2025-02-04T00:40:16Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "OpenAI &quot;We Are On The Wrong Side Of History&quot; (of Open Source)",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/j_R2kk0cMRs/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/j_R2kk0cMRs/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/j_R2kk0cMRs/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-02-04T00:40:16Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "WcXMm1u06DyEaYna1f_NefdDGDA",
            "id": {"kind": "youtube#video", "videoId": "UB8tWlFQ00k"},
            "snippet": {
                "publishedAt": "2025-02-01T01:03:56Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "I just tried o3-mini",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/UB8tWlFQ00k/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/UB8tWlFQ00k/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/UB8tWlFQ00k/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-02-01T01:03:56Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "ZmazDId2ywZ60MaRl1ZqhOgOW3g",
            "id": {"kind": "youtube#video", "videoId": "2D9ON1ZQhnA"},
            "snippet": {
                "publishedAt": "2025-01-30T22:25:27Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "OpenAI Is Actually Terrible",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/2D9ON1ZQhnA/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/2D9ON1ZQhnA/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/2D9ON1ZQhnA/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-01-30T22:25:27Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "jS9uNmb-mdHnHcNqYrDKwDEk1xY",
            "id": {"kind": "youtube#video", "videoId": "GNHuJE_GARc"},
            "snippet": {
                "publishedAt": "2025-01-27T22:38:33Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "I Think I Love Deepseek R1",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/GNHuJE_GARc/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/GNHuJE_GARc/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/GNHuJE_GARc/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-01-27T22:38:33Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "x31fJbkaDK_0AGtDuV4xEuOcXsc",
            "id": {"kind": "youtube#video", "videoId": "ksKzcRfjxpY"},
            "snippet": {
                "publishedAt": "2025-01-25T00:55:37Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "The Secret About Big Software Companies",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/ksKzcRfjxpY/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/ksKzcRfjxpY/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/ksKzcRfjxpY/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-01-25T00:55:37Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "4n9TQAMEal2mBhMSSRWaq4JiynY",
            "id": {"kind": "youtube#video", "videoId": "FINJ0zhdfQ0"},
            "snippet": {
                "publishedAt": "2025-01-22T04:30:09Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Project Stargate - $500,000,000,000 For AI",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/FINJ0zhdfQ0/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/FINJ0zhdfQ0/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/FINJ0zhdfQ0/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-01-22T04:30:09Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "ZRX7iuOCcIOhZOQrSRkcuj_S3nU",
            "id": {"kind": "youtube#video", "videoId": "yt_LWoj7Sjc"},
            "snippet": {
                "publishedAt": "2025-01-07T08:00:52Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "VW Is Recording Your EVERY Movement",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/yt_LWoj7Sjc/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/yt_LWoj7Sjc/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/yt_LWoj7Sjc/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-01-07T08:00:52Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "2AJJfBkDuBor_GGZHnz5-AXZ0p8",
            "id": {"kind": "youtube#video", "videoId": "1Di8X2vRNRE"},
            "snippet": {
                "publishedAt": "2025-01-06T22:46:59Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "I Will Not Write Rust Again",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/1Di8X2vRNRE/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/1Di8X2vRNRE/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/1Di8X2vRNRE/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2025-01-06T22:46:59Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "1Izugwtu-kHXjxC07jgwesE8gUQ",
            "id": {"kind": "youtube#video", "videoId": "BiZ1CLT3nEM"},
            "snippet": {
                "publishedAt": "2024-12-30T20:15:00Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "it&#39;s time for a change",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/BiZ1CLT3nEM/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/BiZ1CLT3nEM/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/BiZ1CLT3nEM/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-30T20:15:00Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "RqHbm2YG0M7_8VipRjcUXfALJYM",
            "id": {"kind": "youtube#video", "videoId": "kjOxkPl3RGo"},
            "snippet": {
                "publishedAt": "2024-12-26T19:41:22Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "are we cooked w/ o3?",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/kjOxkPl3RGo/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/kjOxkPl3RGo/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/kjOxkPl3RGo/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-26T19:41:22Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "ru6Kg59tnQZBdSnNyh1RE2slomw",
            "id": {"kind": "youtube#video", "videoId": "sjz_gupjoJg"},
            "snippet": {
                "publishedAt": "2024-12-21T14:50:37Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "I Made EmojiCode Benchmark And Showed Casey Muratori",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/sjz_gupjoJg/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/sjz_gupjoJg/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/sjz_gupjoJg/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-21T14:50:37Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "Fu6XdVTW4tv8L52Pyf7CxVZzVgs",
            "id": {"kind": "youtube#video", "videoId": "97wr_K8hPNs"},
            "snippet": {
                "publishedAt": "2024-12-19T13:17:07Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "The AI Employee Era Has Begun",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/97wr_K8hPNs/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/97wr_K8hPNs/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/97wr_K8hPNs/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-19T13:17:07Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "286ncFiYU1y5DKYWDM9lgv2ZLP8",
            "id": {"kind": "youtube#video", "videoId": "D2y17cN-i8s"},
            "snippet": {
                "publishedAt": "2024-12-17T18:28:00Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Let&#39;s Have A Chat...",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/D2y17cN-i8s/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/D2y17cN-i8s/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/D2y17cN-i8s/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-17T18:28:00Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "nFf2xVkl4yrdd7Zaw3X0ZaAC3ZI",
            "id": {"kind": "youtube#video", "videoId": "xGaROGmkkxw"},
            "snippet": {
                "publishedAt": "2024-12-14T15:38:12Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "The New Python Based Language",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/xGaROGmkkxw/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/xGaROGmkkxw/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/xGaROGmkkxw/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-14T15:38:12Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "QG55yhW50O87DY4efmq4jX6oWPY",
            "id": {"kind": "youtube#video", "videoId": "MdbhLX67jDY"},
            "snippet": {
                "publishedAt": "2024-12-12T13:54:32Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Popular Python Package Becomes Crypto Miner",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/MdbhLX67jDY/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/MdbhLX67jDY/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/MdbhLX67jDY/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-12T13:54:32Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "iIIoo5tnvfaTZTzw7KmSvv6Mycc",
            "id": {"kind": "youtube#video", "videoId": "vIuHd3N04l0"},
            "snippet": {
                "publishedAt": "2024-12-11T13:07:10Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "ChatGPT o1 Tries To Escape",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/vIuHd3N04l0/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/vIuHd3N04l0/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/vIuHd3N04l0/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-11T13:07:10Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "8csxDG29k_CgCO89FoltrNZCQ34",
            "id": {"kind": "youtube#video", "videoId": "uBYvkg2VXhQ"},
            "snippet": {
                "publishedAt": "2024-12-08T13:01:04Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "friend.com is really bad...",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/uBYvkg2VXhQ/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/uBYvkg2VXhQ/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/uBYvkg2VXhQ/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-08T13:01:04Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "oZ8pyPGlKy_6swJKhGhKjfXEmjs",
            "id": {"kind": "youtube#video", "videoId": "FrFhNe01SOY"},
            "snippet": {
                "publishedAt": "2024-12-07T13:00:24Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "I Created The Best AI Tool Ever",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/FrFhNe01SOY/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/FrFhNe01SOY/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/FrFhNe01SOY/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-12-07T13:00:24Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "6N_k7jKzGm3i5xys3JC9KQXRAhc",
            "id": {"kind": "youtube#video", "videoId": "wf48XDnXtKI"},
            "snippet": {
                "publishedAt": "2024-11-30T13:01:11Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "My Favorite Pastime",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/wf48XDnXtKI/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/wf48XDnXtKI/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/wf48XDnXtKI/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-11-30T13:01:11Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "Fg2FygCBcBroDHmJcdcKGduKPSc",
            "id": {"kind": "youtube#video", "videoId": "f5nGmE92zNA"},
            "snippet": {
                "publishedAt": "2024-11-28T14:47:57Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "PHP 8.4 Is Good",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/f5nGmE92zNA/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/f5nGmE92zNA/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/f5nGmE92zNA/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-11-28T14:47:57Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "bblDAwuz3YmxwsKFNca31rEcvO8",
            "id": {"kind": "youtube#video", "videoId": "KuLUd1UIvVA"},
            "snippet": {
                "publishedAt": "2024-11-23T21:12:47Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "Programming Is Cooked",
                "description": "Twitch https://twitch.tv/ThePrimeagen Discord https://discord.gg/ThePrimeagen Become Backend Dev: https://boot.dev/prime (plus ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/KuLUd1UIvVA/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/KuLUd1UIvVA/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/KuLUd1UIvVA/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-11-23T21:12:47Z",
            },
        },
        {
            "kind": "youtube#searchResult",
            "etag": "UhRT1gRjGoJZw3tvwGflspc_yMI",
            "id": {"kind": "youtube#video", "videoId": "0eHZRPzbiJ0"},
            "snippet": {
                "publishedAt": "2024-11-17T00:35:26Z",
                "channelId": "UCUyeluBRhGPCW4rPe_UvBZQ",
                "title": "TMUX in 100 seconds | Prime Reacts",
                "description": "Recorded live on twitch, GET IN ### Article https://www.youtube.com/watch?v=vtB1J_zCv8I By: Fireship ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/0eHZRPzbiJ0/default.jpg",
                        "width": 120,
                        "height": 90,
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/0eHZRPzbiJ0/mqdefault.jpg",
                        "width": 320,
                        "height": 180,
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/0eHZRPzbiJ0/hqdefault.jpg",
                        "width": 480,
                        "height": 360,
                    },
                },
                "channelTitle": "ThePrimeTime",
                "liveBroadcastContent": "none",
                "publishTime": "2024-11-17T00:35:26Z",
            },
        },
    ],
}
